// Configuration file for LeadListBot Landing Page
// Update these settings to customize your landing page

const CONFIG = {
    // Company Information
    company: {
        name: "LeadListBot",
        tagline: "Automated Lead Generation That Converts",
        description: "Generate high-quality leads for your business with our automated lead generation system. Book a free consultation today."
    },

    // Contact Information
    contact: {
        email: "hello@leadlistbot.com",
        phone: "+1 (555) 123-4567",
        address: "123 Business Ave, Suite 100, City, State 12345"
    },

    // Form Integration (Replace with your actual endpoints)
    forms: {
        // Formspree: https://formspree.io
        formspree: "https://formspree.io/f/YOUR_FORM_ID",
        
        // Alternative: Netlify Forms (just add netlify attribute to form)
        // Alternative: Basin (https://usebasin.com)
        // Alternative: Tally (https://tally.so)
    },

    // Calendly Integration
    calendly: {
        // Replace with your Calendly scheduling URL
        url: "https://calendly.com/your-username/consultation",
        // Event name for tracking
        eventName: "Free Consultation"
    },

    // Analytics & Tracking
    analytics: {
        // Google Tag Manager ID (replace GTM-XXXXXXX)
        gtmId: "GTM-XXXXXXX",
        
        // Google Analytics 4 Measurement ID (if using direct GA4)
        ga4Id: "G-XXXXXXXXXX",
        
        // Facebook Pixel ID (optional)
        facebookPixelId: "",
        
        // LinkedIn Insight Tag ID (optional)
        linkedinId: ""
    },

    // Pricing Plans
    pricing: {
        starter: {
            name: "Starter",
            price: 97,
            features: [
                "Up to 100 leads/month",
                "Basic automation",
                "Email support"
            ]
        },
        professional: {
            name: "Professional",
            price: 297,
            features: [
                "Up to 500 leads/month",
                "Advanced automation",
                "Priority support",
                "CRM integration"
            ],
            popular: true
        },
        enterprise: {
            name: "Enterprise",
            price: 997,
            features: [
                "Unlimited leads",
                "Custom automation",
                "Dedicated manager",
                "White-label option"
            ]
        }
    },

    // Social Proof / Testimonials
    testimonials: [
        {
            name: "Sarah Johnson",
            title: "CEO",
            company: "TechStart Inc.",
            rating: 5,
            text: "LeadListBot increased our qualified leads by 300% in just 30 days. The quality is incredible and the automation saves us hours every week.",
            avatar: "" // Optional: URL to avatar image
        },
        {
            name: "Mike Chen",
            title: "Sales Director",
            company: "GrowthCorp",
            rating: 5,
            text: "Finally, a lead generation tool that actually works. We've closed over $500K in new business from leads generated by LeadListBot.",
            avatar: ""
        },
        {
            name: "Emma Rodriguez",
            title: "Marketing Manager",
            company: "ScaleUp Ltd.",
            rating: 5,
            text: "The ROI is insane. We're getting better leads than our in-house team was finding, and it runs completely on autopilot.",
            avatar: ""
        }
    ],

    // Features
    features: [
        {
            title: "AI-Powered Prospecting",
            description: "Find your ideal customers using advanced AI algorithms that analyze millions of data points to identify high-intent prospects.",
            icon: "chart-bar" // Using Heroicons names
        },
        {
            title: "Automated Outreach",
            description: "Send personalized messages at scale with our smart automation that maintains the human touch your prospects expect.",
            icon: "paper-airplane"
        },
        {
            title: "Intelligent Follow-up",
            description: "Never miss an opportunity with AI-driven follow-up sequences that adapt based on prospect behavior and engagement.",
            icon: "check-circle"
        }
    ],

    // FAQ
    faq: [
        {
            question: "How quickly will I see results?",
            answer: "Most clients start receiving qualified leads within 48-72 hours of setup. We typically see a 200-400% increase in lead volume within the first 30 days."
        },
        {
            question: "What makes your leads higher quality than other services?",
            answer: "Our AI analyzes over 200 data points per prospect including recent company activity, funding events, hiring patterns, and buying signals. We only deliver leads that match your exact criteria and show genuine buying intent."
        },
        {
            question: "Do you offer a money-back guarantee?",
            answer: "Yes! We offer a 30-day money-back guarantee. If you're not satisfied with the quality and quantity of leads, we'll refund your first month payment, no questions asked."
        },
        {
            question: "How does the setup process work?",
            answer: "After booking your consultation, we'll have a 30-minute strategy call to understand your ideal customer profile. Our team then configures your automation and messaging. The entire setup takes 24-48 hours, and we handle everything for you."
        },
        {
            question: "Can I integrate with my existing CRM?",
            answer: "Absolutely! We integrate with all major CRMs including Salesforce, HubSpot, Pipedrive, and more. Leads are automatically synced to your CRM with all relevant data and conversation history."
        }
    ],

    // Design Theme
    theme: {
        colors: {
            primary: "#2563eb",    // Blue
            secondary: "#1e40af",  // Darker blue
            accent: "#f59e0b",     // Orange/Yellow
            success: "#10b981",    // Green
            warning: "#f59e0b",    // Orange
            error: "#ef4444"       // Red
        },
        fonts: {
            primary: "system-ui, -apple-system, sans-serif",
            secondary: "system-ui, -apple-system, sans-serif"
        }
    },

    // Performance Settings
    performance: {
        // Preload important resources
        preloadFonts: [
            // Add font URLs if using web fonts
        ],
        
        // DNS prefetch for external services
        dnsPrefetch: [
            "https://calendly.com",
            "https://formspree.io",
            "https://www.googletagmanager.com",
            "https://www.google-analytics.com"
        ],

        // Image optimization settings
        images: {
            lazyLoad: true,
            webpSupport: true,
            placeholder: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='300' viewBox='0 0 400 300'%3E%3Crect width='400' height='300' fill='%23f3f4f6'/%3E%3Ctext x='50%25' y='50%25' font-size='18' text-anchor='middle' alignment-baseline='middle' font-family='system-ui, sans-serif' fill='%236b7280'%3EImage Placeholder%3C/text%3E%3C/svg%3E"
        }
    },

    // SEO Settings
    seo: {
        title: "LeadListBot - Automated Lead Generation That Converts",
        description: "Generate high-quality leads for your business with our automated lead generation system. Book a free consultation today.",
        keywords: "lead generation, automated leads, B2B leads, sales automation, prospect generation",
        author: "LeadListBot",
        robots: "index, follow",
        ogImage: "/og-image.jpg", // Add your Open Graph image
        twitterCard: "summary_large_image"
    }
};

// Export for use in other files (if using modules)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}

// Make available globally
window.CONFIG = CONFIG;
